name: template
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flex_color_scheme: ^8.0.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  get_it: ^8.0.2
  loader_overlay: ^4.0.3
  mobx: ^2.4.0
  json_annotation: ^4.9.0
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mobx_codegen: ^2.6.2
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
